# Shell variables
# Generated by 'wal'
wallpaper='/home/michael/Pictures/Wallpapers/Rotes_Boot.jpg'

# Special
background='#0b0b1b'
foreground='#d1c7d5'
cursor='#d1c7d5'

# Colors
color0='#0b0b1b'
color1='#544A5F'
color2='#C63547'
color3='#F75763'
color4='#34539B'
color5='#E97984'
color6='#5E97CB'
color7='#d1c7d5'
color8='#928b95'
color9='#544A5F'
color10='#C63547'
color11='#F75763'
color12='#34539B'
color13='#E97984'
color14='#5E97CB'
color15='#d1c7d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
