#!/bin/bash
inputFile="$( echo $1 | sed 's!~!\/home\/michael!')"
[ -z "$inputFile" ] && exit
dir="$(echo '$inputFile' | sed 's![^/]*$!!')"
fileEnd="$(echo "$inputFile" | sed 's!.*\.!\.!')"

case "$fileEnd" in 

	\.tex)
		cd "$dir"
		pdflatex "$inputFile"
		;;
	
	\.ms)
		eqn="$(grep "\.EQ" -i $inputFile | head -1)"
		name="$(echo $inputFile | sed 's/\..*//')"
		cd "$dir"
		[ -z "$eqn" ] || {
		       	groff -e "$inputFile" -ms -Tpdf > "$name.pdf" && exit
		}
		groff -ms "$inputFile" -Tpdf > "$name.pdf" 
esac
