#!/bin/bash
[ "$#" -eq 0 ] && echo "No Instruction Given" && exit

while getopts "f:bs" option
do
	case "${option}" in
		"f")
			location="$OPTARG"
			;;
	
		"b")
			let command=5
			;;

		"s")
			let command=-5
			;;

	esac
done 

cd "$location"
value="$(grep -woP "gappx  = .." config.h | head -1 | cut -d' ' -f4)"

[[ "$value" == 0 ]] && [[ "$command" == -5 ]] && exit
[[ "$value" == 50 ]] && [[ "$command" == 5 ]] && exit

let result=$(($command + $value))

sed -i "s/gappx  = $value/gappx  = $result/" config.h
sudo make install
pkill dwm
